/// \file Level2Search.h
/// \brief Interface for the Level 2 search `CLevel2Search`.

// MIT License
//
// Copyright (c) 2023 Ian Parberry
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
// IN THE SOFTWARE.

#ifndef __Level2Search_h__
#define __Level2Search_h__

#include <set>
#include <vector>

#include "Matching.h"
#include "Defines.h"
#include "Settings.h"

/// \brief Level 2 search.
///
/// Search for a collection of canonical matchings for level 2 of a first
/// normal form sorting network. That is, out of all candidates for level 2
/// generated by permuting the channels in pairs, so that the comparator
/// network stays in first normal form, choose the lexicographically first one.
/// 
/// Consider the sorting network in the figure below (left). We can construct
/// a new sorting network by swapping the pair of green channels with the pair
/// of blue channels. The resulting sorting network on the right has both the
/// min-max comparators that we have used so far (which put the maximum on the
/// bottom channel and the minimum on the top channel), and max-min comparators,
/// which put the maximum on the top channel and the minimum on the bottom
/// channel. See also `C1NF1`. In the figure below (right) the
/// arrows on the comparators point in the direction taken by the maximum.
/// Notice that we have created four max-min comparators and
/// a twist at the end of the channel to keep the outputs in sorted order. 
/// \image html 2NFa.png width=60%
/// We flip the first max-min comparator and the green and blue channels
/// to the right of it (below, left) and make the corresponding twist at the end
/// (below, right).
/// \image html 2NFb.png width=60%
/// We flip the second max-min comparator and the green and blue channels
/// to the right of it (below, left) and make the corresponding twist at the end
/// (below, right).
/// \image html 2NFc.png width=60%
/// We flip the third max-min comparator and the green and blue channels
/// to the right of it (below, left) and make the corresponding twist at the end
/// (below, right).
/// \image html 2NFd.png width=60%
/// We flip the fourth max-min comparator and the green and blue channels
/// to the right of it (below, left) and make the corresponding twist at the end
/// (below, right). Notice that the twists have cancelled out leaving us with
/// a new sorting network that has a different second level than the one we
/// started with.
/// \image html 2NFe.png width=60%
/// Our search therefore needs to include only one of the second level candidates
/// that can be obtained by permuting pairs of channels. In our example above,
/// only one of the two second levels in the figure below need appear in the
/// search. Notice that the comparator networks remain in first normal form.
/// \image html 2NFf.png width=25%
/// This speeds up the search by not having to iterate through all 
/// possibilities for the second level.

class CLevel2Search: public CSettings{
  private:
    std::set<size_t> m_stlUsed; ///< Set of indices of used matchings.
    std::vector<CMatching> m_stlResults; ///< Results.

    size_t Permute(CMatching&, const size_t); ///< Permute the matching.

    size_t GetIndex(CMatching&); ///< Get the index of a matching.
    const size_t GetNumMatchings(const size_t) const; ///< Number of matchings.

  public:
    CLevel2Search(); ///< Constructor.
    
    const std::vector<CMatching>& GetMatchings() const; ///< Get matching vector.
    void Save() const; ///< Save results to log file for debugging purposes.
}; //CLevel2Search

#endif //__Level2Search_h__