/// \file Level2Search.h
/// \brief Interface for the Level 2 search `CLevel2Search`.

// MIT License
//
// Copyright (c) 2023 Ian Parberry
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
// IN THE SOFTWARE.

#ifndef __Level2Search_h__
#define __Level2Search_h__

#include <set>
#include <vector>

#include "Matching.h"
#include "Defines.h"
#include "Settings.h"

/// \brief Level 2 search.
///
/// Search for a collection of canonical matchings for level 2 of a first
/// normal form sorting network. That is, out of all candidates for level 2
/// generated by permuting the channels in pairs, so that the comparator
/// network stays in first normal form, choose the lexicographically first one.

class CLevel2Search: public CSettings{
  private:
    std::set<CMatching> m_stlUsed; ///< Set of used matchings.
    //std::set<size_t> m_stlUsed; ///< Set of indices of used matchings.
    std::vector<CMatching> m_stlResults; ///< Results.
    //size_t m_nCopy[MAXINPUTS + 1] = {0}; ///< Integer copy of matching.

    //size_t Permute(CMatching&, const size_t); ///< Permute the matching.
    CMatching Permute(CMatching&, const size_t); ///< Permute the matching.

    //size_t GetIndex(CMatching&); ///< Get the index of a matching.
    const size_t GetNumMatchings(const size_t) const; ///< Number of matchings.

  public:
    CLevel2Search(); ///< Constructor.
    
    const std::vector<CMatching>& GetMatchings() const; ///< Get matching vector.
}; //CLevel2Search

#endif //__Level2Search_h__